config/routes.rb
Rails.application.routes.draw do
  get "search", to: "search#index"
  get "/about", to: "about#about"
  resources :books, path: "index", only: [ :index, :show ]
  resources :all_books, path: "books", only: [ :index, :show ]
  resources :author, path: "author", only: [ :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "all_books#index"   # << add this line
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books
  has_many :books, through: :author_books
  validates :author_name, :author_key, :biography, presence: true
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :author_books
  has_many :authors, through: :author_books
  validates :title, :work_key, :description, :subject, :first_publish_year, :edition_count, :cover_identifier, presence: true

  def self.ransackable_attributes(auth_object = nil)
    [ "title", "subject" ]
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/all_books_controller.rb
class AllBooksController < ApplicationController
  def index
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true).page(params[:page]).per(15)
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def show
    @author = Author.find(params[:id])
    @books = @author.books
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.includes(:authors).all
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/all_books_helper.rb
module AllBooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/about/about.html.erb
<%content_for :title, "About"%>
<h1 class="block title is-3 mt-5 has-text-centered">About Page</h1>
<%# Project overview %>
<p class="block ml-5">This project utilizies the "Subjects", "Work & Edition", & "Authors" APIs from OpenLibrary's Index of APIS to create a navigable and searchable index of
horror, fantasy, romance, poetry, and thriller books.</p>
<div class="content">
  <ul>
    <%# Subjects API %>
    <li class="block is-family-code">Subjects API - This API is used to fetch data from books that belong to a specific subject/genre.
    It returns the "title", "first_publish_year", "edition_count", "cover_id", "author_key" and "work_key" of each book.</li>
    <%# Work & Edition API %>
    <li class="block is-family-code">Work & Edition API - This API is used to fetch the description of each book since it is not available in the "Subjects API" response.
    It takes the "work_key" from the "Subjects API" response to make a JSON request to the "Work & Edition API" and returns the
    description of each book.
    </li>
    <%# Authors API %>
    <li class="block is-family-code">Authors API - This API is used to fetch data for the author of each book. It takes the "author_key" from the "Subjects API" response to make
      a JSON request to the "Authors API" and returns the "name" and "bio" of each author.
    </li>
  </ul>
</div>
<section class="section is-small has-text-centered">
  <p class="block title">The ERD of the Project:</p>
  <img src="/railsintroERD.png" alt="Intro To Rails Project ERD">
</section>

app/views/all_books/index.html.erb
<% content_for :title, "Books" %>
<h1 class="title is-1 has-text-centered">Our Book Collection</h1>

<!-- Search Form -->
<%= search_form_for @q, url: all_books_path, method: :get do |f| %>
  <div class="is-flex is-justify-content-right">
    <div class="field has-addons mb-5 mr-5">
      <div class="dropdown" id="myDropdown">
        <div class="dropdown-trigger">
          <div class="control">
            <button type="button" class="input has-text-centered" aria-haspopup="true" aria-controls="dropdown-menu">
              <% if params.dig(:q, :subject_eq).present? %>
                <span class="is-capitalized"><%= params[:q][:subject_eq] %></span>
              <% else %>
                <span>Filter By</span>
              <% end %>
              <span class="icon is-small">
                <i class="fas fa-angle-down" aria-hidden="true"></i>
              </span>
            </button>
          </div>
        </div>
        <div class="dropdown-menu" id="dropdown-menu" role="menu">
          <div class="dropdown-content">
            <%= f.select :subject_eq,
                  options_for_select(Book.pluck(:subject).uniq, @q.subject_eq),
                  { include_blank: "Select a Genre" },
                  class: "input is-capitalized" %>
          </div>
        </div>
      </div>
      <div class="control">
        <%= f.search_field :title_cont, class: "input", placeholder: "Search by Title" %>
      </div>
      <div class="control">
        <%= f.submit "Search", class: "button is-info" %>
      </div>
    </div>
  </div>
<% end %>
<!-- Display Books (Search Results OR All Books) -->
<% if @books.any? %>
  <% if params[:q].present? %>
    <%= link_to "< All Books", all_books_path, class: "ml-5" %>
  <% end %>
  <div class="grid is-col-min-12 mt-5">
    <% @books.each do |book| %>
      <div class="cell ml-5">
        <img style="width: 180px; height: 280px; object-fit: cover;"
             src="https://covers.openlibrary.org/b/id/<%= book.cover_identifier %>-M.jpg"
             alt="<%= book.title %> Cover Art">
        <p><%= link_to book.title, book %></p>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No books found matching your search.</p>
<% end %>

<!-- Pagination -->
<div class="pagination is-flex is-justify-content-center mt-5 mb-5">
  <%= paginate @books %>
</div>

app/views/all_books/show.html.erb
<%content_for(:html_title){@book.title}%>
<h1 class="title is-2 ml-5"><%=@book.title%></h1>
<div class="columns">
  <div class="column is-flex is-justify-content-space-between">
    <img style="width: 300px; height: 400px; object-fit: cover;" class="ml-5" src="https://covers.openlibrary.org/b/id/<%=@book.cover_identifier%>-L.jpg" alt="<%=@book.title%> Cover Art">
    <ul>
      <li style="width: 80%;" class="block is-family-code ml-5 is-size-5"><%=@book.description%></li>
      <li class="is-family-code ml-5 is-size-5">Author(s):</li>
      <%@book.authors.each do |author|%>
        <li class="is-family-code ml-5 is-size-5"><%= link_to author.author_name, author%></li>
      <%end%>
      <li class="block is-family-code ml-5 mt-5 is-size-5">First Publish Year: <%=@book.first_publish_year%></li>
      <li class="block is-family-code ml-5 is-size-5">Edition Count: <%=@book.edition_count%></li>
      <li class="block is-family-code is-capitalized ml-5 is-size-5">Genre: <%=@book.subject%></li>
    </ul>
  </div>
</div>

app/views/author/show.html.erb
<%content_for :title, @author.author_name%>
<h1 class="title is-2 ml-5"><%=@author.author_name%></h1>
<div class="columns">
  <div class="column is-flex is-justify-content-space-between">
  <p style="width: 80%;" class="block is-family-code ml-5 is-size-5"><%=@author.biography%></p>
  </div>
</div>
<div class="grid is-col-min-12 mt-5">
  <% @books.each do |book| %>
    <div class="cell ml-5">
      <img style="width: 180px; height: 280px; object-fit: cover;"
      src="https://covers.openlibrary.org/b/id/<%= book.cover_identifier %>-M.jpg"
      alt="<%= book.title %> Cover Art">
      <p><%= link_to book.title, book %></p>
    </div>
    <% end %>
</div>

app/views/books/index.html.erb
<%content_for :title, "Home"%>
<div class="container">
  <%@books.group_by(&:subject).each do |subject, books|%>
    <section class="hero is-info is-small">
      <div class="hero-body is-flex is-justify-content-space-between">
        <h3 class=" is-size-5 has-text-weight-bold is-capitalized"><%=subject%> Books</h3>
        <%= link_to "See More >", all_books_path(q: { subject_eq: "#{subject}" }), class: "ml-5" %>
      </div>
    </section>
    <div class="columns mt-5">
          <% books.first(5).each do |book| %>
            <div class="column is-flex-direction-column">
              <img style="width: 180px; height: 280px; object-fit: cover;" src="https://covers.openlibrary.org/b/id/<%=book.cover_identifier%>-M.jpg" alt="<%=book.title%> Cover Art">
              <p class=""><%= link_to book.title, book%></p>
            </div>
          <%end%>
  </div>
  <% end %>
</div>

app/views/books/show.html.erb
<%content_for :title, @book.title%>
<h1 class="title is-2 ml-5"><%=@book.title%></h1>
<div class="columns">
  <div class="column is-flex is-justify-content-space-between">
    <img style="width: 300px; height: 400px; object-fit: cover;" class="ml-5" src="https://covers.openlibrary.org/b/id/<%=@book.cover_identifier%>-L.jpg" alt="<%=@book.title%> Cover Art">
    <ul>
      <li style="width: 80%;" class="block is-family-code ml-5 is-size-5"><%=@book.description%></li>
      <li class="is-family-code ml-5 is-size-5">Author(s):</li>
      <%@book.authors.each do |author|%>
        <li class="is-family-code ml-5 is-size-5"><%= link_to author.author_name, author%></li>
      <%end%>
      <li class="block is-family-code ml-5 mt-5 is-size-5">First Publish Year: <%=@book.first_publish_year%></li>
      <li class="block is-family-code ml-5 is-size-5">Edition Count: <%=@book.edition_count%></li>
      <li class="block is-family-code is-capitalized ml-5 is-size-5">Genre: <%=@book.subject%></li>
    </ul>
  </div>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar is-link mb-5" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item has-text-weight-bold is-family-code">OpenLibrary API Project</a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    <%= link_to "Home", "/index", class: "navbar-item" %>

    <%= link_to "Books", "/books", class: "navbar-item" %>

    <%= link_to "About", "/about", class: "navbar-item" %>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css"
    >
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "common/navbar" %>
    <%= yield %>
  </body>
</html>